name: Executa meu_executavel.exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executa meu_executavel.exe
        run: meu_executavel.exe
